version: '3'
services:
  server:
    container_name: intsights-server
    build:
      context: ./server/.
      dockerfile: dockerfile
    environment:
      - mongodb=mongodb
    ports:
      - 1337:1337
  mongodb:
    container_name: intsights-mongo
    image: mongo:latest

  mongo_seed:
    container_name: intsights-mongo-seed
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./scripts:/scripts
      - ./server/assets:/seed
    command:
      /scripts/import.sh

  client:
    container_name: intsight-client
    build:
      context: ./client/.
      dockerfile: dockerfile
    ports:
     - 4200:4200
